apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: iot-analytics
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    
    scrape_configs:
      - job_name: 'go-microservice-pods'
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names: ['iot-analytics']
        
        relabel_configs:
          # БЕРЁМ ТОЛЬКО ПОДЫ С АННОТАЦИЕЙ prometheus.io/scrape="true"
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
            action: keep
            regex: true
          
          # БЕРЁМ ПОРТ ИЗ АННОТАЦИИ ИЛИ ИСПОЛЬЗУЕМ ПОРТ КОНТЕЙНЕРА
          - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
            action: replace
            regex: ([^:]+)(?::\d+)?;(\d+)
            replacement: $1:$2
            target_label: __address__
          
          # БЕРЁМ ПУТЬ К МЕТРИКАМ
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
            action: replace
            target_label: __metrics_path__
            regex: (.+)
          
          # ДОБАВЛЯЕМ ЛЕЙБЛЫ
          - action: labelmap
            regex: __meta_kubernetes_pod_label_(.+)
          
          - source_labels: [__meta_kubernetes_namespace]
            action: replace
            target_label: namespace
          
          - source_labels: [__meta_kubernetes_pod_name]
            action: replace
            target_label: pod